apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
  name: custom-logo
  namespace: openshift-config
binaryData:
  logo.png: {{ .Files.Get "assets/ice-logo.png" | b64enc }}
